services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Forum Services
    App\SharedKernel\:
        resource: '../../src/SharedKernel/*'

    # Event Dispatcher
    App\SharedKernel\Domain\Interface\EventDispatcherInterface:
        alias: App\SharedKernel\Infrastructure\Event\SymfonyEventDispatcher




