aws:
    version: latest
    region: '%env(AWS_REGION)%'
    endpoint: '%env(AWS_S3_ENDPOINT)%'
    use_path_style_endpoint: true
    credentials:
        key: "%env(AWS_KEY)%"
        secret: "%env(AWS_SECRET)%"
