doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_mysql
                url: '%env(resolve:DATABASE_URL)%'
                charset: UTF8MB4
                mapping_types:
                    enum: string
            dwh:
                driver: pdo_mysql
                url: '%env(resolve:DATABASE_URL_DWH)%'
                charset: UTF8
                mapping_types:
                    enum: string
            audit:
                driver: pdo_mysql
                url: '%env(resolve:DATABASE_URL_AUDIT)%'
                charset: UTF8
                mapping_types:
                    enum: string
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                validate_xml_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                identity_generation_preferences:
                    Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
                auto_mapping: true
                mappings:
                    UserDomain:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/BoundedContext/User/Domain'
                        prefix: 'App\BoundedContext\User\Domain'
                        alias: UserDomain
                    SharedKernel:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/SharedKernel'
                        prefix: 'App\SharedKernel'
                        alias: SharedKernel
                dql:
                    string_functions:
                        ifnull: DoctrineExtensions\Query\Mysql\IfNull
                    numeric_functions:
                        round: DoctrineExtensions\Query\Mysql\Round
                    datetime_functions:
                        date_diff: DoctrineExtensions\Query\Mysql\DateDiff
        resolve_target_entities: ~

when@prod:
    doctrine:
        orm:
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
