framework:
    rate_limiter:
        # Register : 3 comptes / heure par IP
        register:
            policy: sliding_window
            limit: 3
            interval: '1 hour'

when@test:
    framework:
        rate_limiter:
            register:
                policy: no_limit
