twig:
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/src/SharedKernel/Presentation/Resources/views': 'SharedKernel'
        '%kernel.project_dir%/src/BoundedContext/User/Presentation/Resources/views': 'User'
        '%kernel.project_dir%/src/BoundedContext/Article/Presentation/Resources/views': 'Article'
        '%kernel.project_dir%/src/BoundedContext/Forum/Presentation/Resources/views': 'Forum'
        '%kernel.project_dir%/src/BoundedContext/VideoGamesRecords/Core/Presentation/Resources/views': 'VideoGamesRecordsCore'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
        - '@A2lixTranslationForm/bootstrap_5_layout.html.twig'

when@test:
    twig:
        strict_variables: true
