ALTER TABLE vgr_team ADD forum_id INT DEFAULT NULL;
ALTER TABLE vgr_team ADD CONSTRAINT FK_5801B8C629CCBAD0 FOREIGN KEY (forum_id) REFERENCES pnf_forum (id) ON DELETE SET NULL;
CREATE UNIQUE INDEX UNIQ_5801B8C629CCBAD0 ON vgr_team (forum_id);
