# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

imports:
    - { resource: services/shared.yaml }
    - { resource: services/user.yaml }
    - { resource: services/article.yaml }
    - { resource: services/forum.yaml }
    - { resource: services/vgr/shared.yaml }
    - { resource: services/vgr/igdb.yaml }
    - { resource: services/vgr/core.yaml }
    - { resource: services/vgr/badge.yaml }
    - { resource: admin/user.yml }
    - { resource: admin/article.yml }
    - { resource: admin/forum.yml }
    - { resource: admin/vgr/igdb.yml }
    - { resource: admin/vgr/core.yml }
    - { resource: admin/vgr/badge.yml }


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # SharedKernel services only - Bounded Contexts are autonomous
    App\SharedKernel\:
        resource: '../src/SharedKernel/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\SharedKernel\Infrastructure\Messenger\Middleware\UniquenessMiddleware:
        arguments:
            $cache: '@cache.app'
            $ttl: 3600
