services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\BoundedContext\VideoGamesRecords\Badge\:
        resource: '../../../src/BoundedContext/VideoGamesRecords/Badge/*'

