services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Article Domain Services
    App\BoundedContext\VideoGamesRecords\Proof\:
        resource: '../../../src/BoundedContext/VideoGamesRecords/Proof/*'


    App\BoundedContext\VideoGamesRecords\Proof\Presentation\Web\Controller\PictureShow:
        arguments:
            $projectDir: '%kernel.project_dir%'

    # Sonata Block Services
    admin.block.service.proof.games:
        class: App\BoundedContext\VideoGamesRecords\Proof\Presentation\Block\Service\ProofGamesBlockService
        tags:
            - { name: "sonata.block" }

    admin.block.service.proof_requests:
        class: App\BoundedContext\VideoGamesRecords\Proof\Presentation\Block\Service\ProofRequestBlockService
        tags:
            - { name: "sonata.block" }
