services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\BoundedContext\VideoGamesRecords\Shared\:
        resource: '../../../src/BoundedContext/VideoGamesRecords/Shared/*'
