services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $storagePublicUrl: '%env(PICTURE_PUBLIC_URL)%'

  App\BoundedContext\VideoGamesRecords\Team\:
    resource: '../../../src/BoundedContext/VideoGamesRecords/Team/*'

